-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 21:13:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dispositivos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dispositivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dispositivos` DEFAULT CHARACTER SET utf8 ;
USE `dispositivos` ;

-- -----------------------------------------------------
-- Table `dispositivos`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispositivos`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `cargo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personas_cargos1_idx` (`cargo_id` ASC) ,
  CONSTRAINT `fk_personas_cargos1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `dispositivos`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispositivos`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`dispositivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mac` LONGTEXT NOT NULL,
  `nombre` LONGTEXT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivos_personas1_idx` (`persona_id` ASC) ,
  CONSTRAINT `fk_dispositivos_personas1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `dispositivos`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispositivos`.`ips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`ips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitud` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispositivos`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`estados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dispositivos`.`conexiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispositivos`.`conexiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dispositivo_id` INT NOT NULL,
  `ip_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivos_has_ips_ips1_idx` (`ip_id` ASC) ,
  INDEX `fk_dispositivos_has_ips_dispositivos1_idx` (`dispositivo_id` ASC) ,
  INDEX `fk_conexiones_estados1_idx` (`estado_id` ASC) ,
  CONSTRAINT `fk_dispositivos_has_ips_dispositivos1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `dispositivos`.`dispositivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispositivos_has_ips_ips1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `dispositivos`.`ips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conexiones_estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `dispositivos`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
